### PR TITLE
Update with changes in Sveltekit

### PR DESCRIPTION
**Pull request by rgieseke**
I've tried to update to the recent changes in Sveltekit's folder structure and vite usage. 
There were some changes necessary in the CSS, not sure if there is a better solution for these.

### CODE REVIEW

**Comment by rgieseke** [comment]
Updated with Sveltekit 1.0.0 and Layercake 7.1.0

**Comment by mhkeller** [comment]
Sorry I missed this from before. I’ll give it a look this weekend!

**Comment by mhkeller** [comment]
Thanks for putting it together!

**Comment by mhkeller** [comment]
Thanks again for doing this. I updated the readme with the new ports that vite uses instead of `5000` and `3000`. I was getting a warning that...

```
Your tsconfig.json should extend the configuration generated by SvelteKit:
{
  "extends": "./.svelte-kit/tsconfig.json"
}
```

... so I added that to the tsconfig.json. I'll merge this and if you see anything else that needs updating let me know. Do you have any interest in updating the main layercake.graphics site to use 1.0?

**Comment by rgieseke** [comment]
> Do you have any interest in updating the main layercake.graphics site to use 1.0?

Happy to!

**Pull request merged**
